const GET_SELECTED_IMAGES = 'GET_SELECTED_IMAGES'
const TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE'
const TOGGLE_UPLOADER = 'TOGGLE_UPLOADER'
const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
const FINISH_UPLOADING = 'FINISH_UPLOADING'
const FETCHED_CLOTHES = 'FETCHED_CLOTHES'

export {
  GET_SELECTED_IMAGES,
  TOGGLE_SHUFFLE,
  TOGGLE_UPLOADER,
  UPLOAD_IMAGE,
  FINISH_UPLOADING,
  FETCHED_CLOTHES
}