export default {
  num: 0,
  selected: [],
  uploaderActive: false,
  uploading: false,
  clothes: [],
  tops: [],
  bottoms: [],
  shoes: [],
  uploadButton: true,
  shuffling: false,
  url: '',
  selectedType: '',
  categorize: false,
  animating: false,
}